"""initial migration

Revision ID: 47bf113d1142
Revises: 
Create Date: 2026-03-27 04:34:45.200140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47bf113d1142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('idx_auth_sessions_user_id'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_chat_messages_session_id_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_user_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.drop_index(op.f('idx_chat_sessions_user_updated'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('uq_course_offerings_enrollment_key'), table_name='course_offerings')
    op.create_index(op.f('ix_course_offerings_course_code'), 'course_offerings', ['course_code'], unique=False)
    op.create_index(op.f('ix_course_offerings_lecturer_user_id'), 'course_offerings', ['lecturer_user_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_term'), 'course_offerings', ['term'], unique=False)
    op.create_unique_constraint(None, 'course_offerings', ['enrollment_key'])
    op.create_index(op.f('ix_enrollment_events_actor_user_id'), 'enrollment_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_enrollment_events_enrollment_id'), 'enrollment_events', ['enrollment_id'], unique=False)
    op.drop_index(op.f('idx_enrollment_roadmap_progress_enrollment'), table_name='enrollment_roadmap_progress')
    op.drop_index(op.f('idx_enrollment_roadmap_progress_item'), table_name='enrollment_roadmap_progress')
    op.add_column('enrollment_task_results', sa.Column('score_source', sa.Enum('manual', 'ai_accepted', 'hybrid', 'legacy', name='attempt_score_source'), nullable=True))
    op.add_column('enrollment_task_results', sa.Column('grading_scheme_version_id', sa.UUID(), nullable=True))
    op.add_column('enrollment_task_results', sa.Column('latest_ai_evaluation_id', sa.UUID(), nullable=True))
    op.add_column('enrollment_task_results', sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrollment_task_results', sa.Column('submission_text', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_enrollment_task_results_enrollment'), table_name='enrollment_task_results')
    op.drop_index(op.f('idx_enrollment_task_results_task'), table_name='enrollment_task_results')
    op.create_index('idx_enrollment_task_latest_ai_eval', 'enrollment_task_results', ['latest_ai_evaluation_id'], unique=False)
    op.create_index('idx_enrollment_task_scheme', 'enrollment_task_results', ['grading_scheme_version_id'], unique=False)
    op.create_index(op.f('ix_enrollment_task_results_grading_scheme_version_id'), 'enrollment_task_results', ['grading_scheme_version_id'], unique=False)
    op.create_index(op.f('ix_enrollment_task_results_latest_ai_evaluation_id'), 'enrollment_task_results', ['latest_ai_evaluation_id'], unique=False)
    op.create_index(op.f('ix_enrollment_task_results_score_source'), 'enrollment_task_results', ['score_source'], unique=False)
    op.create_foreign_key(None, 'enrollment_task_results', 'task_grading_scheme_versions', ['grading_scheme_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_enrollment_task_results_latest_ai_evaluation', 'enrollment_task_results', 'attempt_ai_evaluations', ['latest_ai_evaluation_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_index(op.f('uq_enrollment_unique'), table_name='enrollments')
    op.create_unique_constraint('uq_enrollment_unique', 'enrollments', ['offering_id', 'user_id'])
    op.create_index(op.f('ix_enrollments_offering_id'), 'enrollments', ['offering_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.drop_index(op.f('idx_ingested_documents_hash'), table_name='ingested_documents')
    op.drop_index(op.f('idx_ingested_documents_status'), table_name='ingested_documents')
    op.drop_index(op.f('idx_ingested_documents_uploader'), table_name='ingested_documents')
    op.alter_column('notifications', 'channel',
               existing_type=postgresql.ENUM('in_app', 'email', 'push', name='notification_channel'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('roadmap_assessment_tasks', sa.Column('current_grading_scheme_version_id', sa.UUID(), nullable=True))
    op.create_index('idx_roadmap_tasks_current_scheme', 'roadmap_assessment_tasks', ['current_grading_scheme_version_id'], unique=False)
    op.create_index(op.f('ix_roadmap_assessment_tasks_current_grading_scheme_version_id'), 'roadmap_assessment_tasks', ['current_grading_scheme_version_id'], unique=False)
    op.create_foreign_key('fk_roadmap_tasks_current_grading_scheme_version', 'roadmap_assessment_tasks', 'task_grading_scheme_versions', ['current_grading_scheme_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_index(op.f('ix_student_badges_user_id'), 'student_badges', ['user_id'], unique=False)
    op.create_index(op.f('ix_xp_events_enrollment_id'), 'xp_events', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_enrollment_id'), table_name='xp_events')
    op.drop_index(op.f('ix_student_badges_user_id'), table_name='student_badges')
    op.drop_constraint('fk_roadmap_tasks_current_grading_scheme_version', 'roadmap_assessment_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_roadmap_assessment_tasks_current_grading_scheme_version_id'), table_name='roadmap_assessment_tasks')
    op.drop_index('idx_roadmap_tasks_current_scheme', table_name='roadmap_assessment_tasks')
    op.drop_column('roadmap_assessment_tasks', 'current_grading_scheme_version_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('notifications', 'channel',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('in_app', 'email', 'push', name='notification_channel'),
               existing_nullable=False)
    op.create_index(op.f('idx_ingested_documents_uploader'), 'ingested_documents', ['uploader_user_id'], unique=False)
    op.create_index(op.f('idx_ingested_documents_status'), 'ingested_documents', ['status'], unique=False)
    op.create_index(op.f('idx_ingested_documents_hash'), 'ingested_documents', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_offering_id'), table_name='enrollments')
    op.drop_constraint('uq_enrollment_unique', 'enrollments', type_='unique')
    op.create_index(op.f('uq_enrollment_unique'), 'enrollments', ['offering_id', 'user_id'], unique=True)
    op.drop_constraint('fk_enrollment_task_results_latest_ai_evaluation', 'enrollment_task_results', type_='foreignkey')
    op.drop_constraint(None, 'enrollment_task_results', type_='foreignkey')
    op.drop_index(op.f('ix_enrollment_task_results_score_source'), table_name='enrollment_task_results')
    op.drop_index(op.f('ix_enrollment_task_results_latest_ai_evaluation_id'), table_name='enrollment_task_results')
    op.drop_index(op.f('ix_enrollment_task_results_grading_scheme_version_id'), table_name='enrollment_task_results')
    op.drop_index('idx_enrollment_task_scheme', table_name='enrollment_task_results')
    op.drop_index('idx_enrollment_task_latest_ai_eval', table_name='enrollment_task_results')
    op.create_index(op.f('idx_enrollment_task_results_task'), 'enrollment_task_results', ['task_id'], unique=False)
    op.create_index(op.f('idx_enrollment_task_results_enrollment'), 'enrollment_task_results', ['enrollment_id'], unique=False)
    op.drop_column('enrollment_task_results', 'submission_text')
    op.drop_column('enrollment_task_results', 'finalized_at')
    op.drop_column('enrollment_task_results', 'latest_ai_evaluation_id')
    op.drop_column('enrollment_task_results', 'grading_scheme_version_id')
    op.drop_column('enrollment_task_results', 'score_source')
    op.create_index(op.f('idx_enrollment_roadmap_progress_item'), 'enrollment_roadmap_progress', ['roadmap_item_id'], unique=False)
    op.create_index(op.f('idx_enrollment_roadmap_progress_enrollment'), 'enrollment_roadmap_progress', ['enrollment_id'], unique=False)
    op.drop_index(op.f('ix_enrollment_events_enrollment_id'), table_name='enrollment_events')
    op.drop_index(op.f('ix_enrollment_events_actor_user_id'), table_name='enrollment_events')
    op.drop_constraint(None, 'course_offerings', type_='unique')
    op.drop_index(op.f('ix_course_offerings_term'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_lecturer_user_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_course_code'), table_name='course_offerings')
    op.create_index(op.f('uq_course_offerings_enrollment_key'), 'course_offerings', ['enrollment_key'], unique=True)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index(op.f('idx_chat_sessions_user_updated'), 'chat_sessions', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_session_id_id'), 'chat_messages', ['session_id', 'id'], unique=False)
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.create_index(op.f('idx_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    # ### end Alembic commands ###
